name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the CMakeLists.txt file relative to the root of the project.
  CMAKE_SOURCE_DIR: .

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release, Debug]
        architecture: [x64, x86]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install Dependencies
      run: sudo apt-get install -y cmake g++

    # Configure CMake project
    - name: CMake Configure
      run: |
        cmake -S ${{env.CMAKE_SOURCE_DIR}} -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_FLAGS=-m${{matrix.architecture}} -DCMAKE_CXX_FLAGS=-m${{matrix.architecture}}

    # Build the project
    - name: CMake Build
      run: cmake --build build --config ${{matrix.build_type}}

    # Optionally, run tests (if applicable)
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
